export const COMMON_INGREDIENTS = [
  "Eggs",
  "Milk",
  "Butter",
  "Flour",
  "Sugar",
  "Salt",
  "Pepper",
  "Olive Oil",
  "Garlic",
  "Onion",
  "Tomato",
  "Potato",
  "Carrot",
  "Chicken",
  "Beef",
  "Pork",
  "Fish",
  "Shrimp",
  "Rice",
  "Pasta",
  "Bread",
  "Cheese",
  "Yogurt",
  "Cream",
  "Lemon",
  "Lime",
  "Basil",
  "Parsley",
  "Thyme",
  "Oregano",
  "Paprika",
  "Cumin",
  "Cinnamon",
  "Vanilla",
  "Chocolate",
  "Honey",
  "Soy Sauce",
  "Vinegar",
  "Mustard",
  "Mayonnaise",
  "Ketchup",
  "Bell Pepper",
  "Zucchini",
  "Broccoli",
  "Spinach",
  "Lettuce",
  "Cucumber",
  "Avocado",
  "Banana",
  "Apple",
  "Orange",
  "Strawberry",
  "Blueberry",
  "Nuts",
  "Almonds",
  "Walnuts",
  "Peanuts",
  "Beans",
  "Lentils",
  "Chickpeas",
  "Corn",
  "Mushroom",
  "Bacon",
  "Ham",
  "Salmon",
  "Tuna",
  "Coconut Milk",
  "Ginger",
  "Chili",
  "Mozzarella",
  "Parmesan",
  "Feta",
  "Tofu",
  "Quinoa",
  "Oats",
];

export const DISH_TYPES = [
  { id: "breakfast", label: "Breakfast", emoji: "🍳" },
  { id: "lunch", label: "Lunch", emoji: "🥗" },
  { id: "dinner", label: "Dinner", emoji: "🍽️" },
  { id: "dessert", label: "Dessert", emoji: "🍰" },
  { id: "snack", label: "Snack", emoji: "🍿" },
  { id: "appetizer", label: "Appetizer", emoji: "🥟" },
  { id: "soup", label: "Soup", emoji: "🍜" },
  { id: "salad", label: "Salad", emoji: "🥗" },
  { id: "pasta", label: "Pasta", emoji: "🍝" },
  { id: "pizza", label: "Pizza", emoji: "🍕" },
  { id: "sandwich", label: "Sandwich", emoji: "🥪" },
  { id: "beverage", label: "Beverage", emoji: "🥤" },
];

export const DIETARY_PREFERENCES = [
  { id: "vegetarian", label: "Vegetarian", emoji: "🥬" },
  { id: "vegan", label: "Vegan", emoji: "🌱" },
  { id: "gluten-free", label: "Gluten-Free", emoji: "🌾" },
  { id: "dairy-free", label: "Dairy-Free", emoji: "🥛" },
  { id: "nut-free", label: "Nut-Free", emoji: "🥜" },
  { id: "low-carb", label: "Low-Carb", emoji: "🥩" },
  { id: "keto", label: "Keto", emoji: "🥑" },
  { id: "paleo", label: "Paleo", emoji: "🦴" },
  { id: "halal", label: "Halal", emoji: "☪️" },
  { id: "kosher", label: "Kosher", emoji: "✡️" },
];
